name: magnify-dashboard
region: nyc # Choose the region closest to your users
services:
  - name: magnify-dashboard
    github:
      branch: main
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile
    http_port: 8501
    health_check:
      http_path: /
    instance_size_slug: basic-s # Basic instance (1GB RAM, 1vCPU)
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0 